### ISSUE TITLE
warning when writing out point_series

### ISSUE THREAD

**Issue by abostroem** [datacarpentry/astronomy-python#160]
I get the following `PerformanceWarning`, maybe we should alert users

```
/Users/bostroem/opt/anaconda3/envs/AstronomicalData2/lib/python3.9/site-packages/pandas/core/generic.py:2606: PerformanceWarning: 
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed-integer,key->values] [items->None]

  pytables.to_hdf(
```

**Comment by rudyphd** [comment]
This issue occurs in episode 5. There is a note on the instructors guide: This warning is saying that pickle will be slow for large objects. We do not need to worry about this since the objects we are saving are small. 

There is an old a panda's issue that suggests using format='table' when saving the file might solve this. Can we get a test of this potential fix?
