### ISSUE TITLE
Fix display of numpy warning

### ISSUE THREAD

**Issue by abostroem** [datacarpentry/astronomy-python#162]
This is purely cosmetic - but in the call out about the numpy warning the warning text goes off page

**Comment by rkotulla** [comment]
I've tried playing around with different options, but none of them seem just right, and it's only an issue if you make the window rather narrow. Possible solutions would be:

1) replace the "site-packages/numpy/lib/function_base.py:4650:" part with just ... since it's the UserWarning part that's important, not so much what exact file and line caused it

2) Insert a linebreak after :4650:

Personally I don't really have a preference for either one, so I bounce that back to you.

**Comment by rudyphd** [comment]
I'll insert the linebreak after :4650:, thanks @rkotulla ! 

Assigned to @rudyphd
